### novosibirsk, (USD)
GET http://localhost:8080/search?region=novosibirsk

### novosibirsk, (USD)
GET http://localhost:8080/search?region=novosibirsk&sort=by-buy

### novosibirsk, (USD)
GET http://localhost:8080/search?region=novosibirsk&sort=by-sell

### novosibirsk, CNY
GET http://localhost:8080/search?region=novosibirsk&currency=CNY

### (moskva, USD)
GET http://localhost:8080/search/

### moskva, (USD)
GET http://localhost:8080/search/?region=moskva

### (moskva), BYN
GET http://localhost:8080/search/?currency=BYN

### moskva, EUR
GET http://localhost:8080/search/?region=moskva&currency=EUR